Symfony/BiblioSF6/src/Entity/Emprunt.php
<?php

namespace App\Entity;

use App\Repository\EmpruntRepository;
use DateTime;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmpruntRepository::class)]
class Emprunt
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date_emprunt = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $date_retour = null;

    #[ORM\ManyToOne(inversedBy: 'emprunts')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Livre $livre = null;

    #[ORM\ManyToOne(inversedBy: 'emprunts')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Abonne $abonne = null;

    // public function __construct()
    // {
    //     // $this->date_emprunt = new DateTimeImmutable("now");
    // }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEmprunt(): ?\DateTimeImmutable
    {
        return $this->date_emprunt;
    }

    public function setDateEmprunt(\DateTimeImmutable $date_emprunt): static
    {
        $this->date_emprunt = $date_emprunt;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeImmutable
    {
        return $this->date_retour;
    }

    public function setDateRetour(?\DateTimeImmutable $date_retour): static
    {
        $this->date_retour = $date_retour;

        return $this;
    }

    public function getLivre(): ?Livre
    {
        return $this->livre;
    }

    public function setLivre(?Livre $livre): static
    {
        $this->livre = $livre;

        return $this;
    }

    public function getAbonne(): ?Abonne
    {
        return $this->abonne;
    }

    public function setAbonne(?Abonne $abonne): static
    {
        $this->abonne = $abonne;

        return $this;
    }
}

Symfony/BiblioSF6/src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Emprunt;
use App\Entity\Livre;
use App\Repository\LivreRepository;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/profile')]
final class ProfilController extends AbstractController
{
    #[Route(name: 'app_profil')]
    // On va vouloir sur l'index du profil, afficher les informations de l'utilisateur et de ses emprunts 
    public function index(): Response
    {
        // La ligne ci dessous n'est pas utile dans le cas de Symfony
        $abonneConnecte = $this->getUser();
        // En effet, dans Symfony, tout comme dans notre menu, je peux récupérer l'entité user via app.user
        // Dans notre cas, c'est notre entité abonné qui est le user ! Je peux ainsi récupérer toutes ses informations dans app.user 
        // $listeEmprunts = $abonneConnecte->getEmprunts();

        return $this->render('profil/index.html.twig', []);
    }

    // Une route pour permettre à l'utilisateur d'emprunter un livre (fictivement, car on s'attend à ce qu'il soit présent à la bibliothèque avec un employé pour emprunter un livre, ensuite, libre à nous de réfléchir à des améliorations de notre système)

    #[Route('/emprunter/{id}', name: 'app_profil_emprunter')]
    public function emprunter(Livre $livre, EntityManagerInterface $em, LivreRepository $lr)
    {

        $livres_non_dispo = $lr->livresNonDisponibles();

        // dd($livres_non_dispo);

        if (!in_array($livre, $livres_non_dispo)) {

            $emprunt = new Emprunt;
            $emprunt->setAbonne($this->getUser());
            $emprunt->setDateEmprunt(new DateTimeImmutable("now"));
            $emprunt->setLivre($livre);

            $em->persist($emprunt);
            $em->flush();

            $this->addFlash("success", "Le livre " . $livre->getTitre() . " de " . $livre->getAuteur() . " a bien été emprunté");
            return $this->redirectToRoute("app_profil");
        } else {
            $this->addFlash("danger", "Le livre " . $livre->getTitre() . " de " . $livre->getAuteur() . " n'est pas disponible !");
            return $this->redirectToRoute("app_home");
        }
    }
}

Symfony/BiblioSF6/templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil
{% endblock %}

{% block titreH1 %}Mon Profil
{% endblock %}

{% block body %}

	{# Ici je dis bonjour avec le pseudo de l'utilisateur #}
	<h2>Bonjour,
		{{app.user.pseudo}}
	</h2>

	<ul class="list-group">
		<li class="list-group-item">{{app.user.nom}}</li>
		<li class="list-group-item">{{app.user.prenom}}</li>
	</ul>

	<h3>Mes emprunts</h3>
	<table class="table table-striped">
		<thead>
			<th>Livre</th>
			<th>Catégorie</th>
			<th>Emprunté le</th>
			<th>Rendu le</th>
		</thead>
		<tbody>
        {# Dans l'abonné ici représenté par app.user, j'ai accès à ses emprunts grâce à la jointure, je peux donc récupérer les emprunts et les afficher #}

        {# 
        Ici on récupère à partir du user connecté donc app.user, ses emprunts, les livres concernés par ces emprunts, ainsi que les catégories des livres en question.
        En bref, en une seule instruction on récupère les données de nos 4 tables différentes ! 
        Si on voulait lancer à la main une requête récupérant toutes ces informations là... Attention la jointure ! 
        Voilà la requête qu'il aurait fallu lancer 
        SELECT abonne.pseudo, abonne.nom, abonne.prenom, livre.titre, livre.auteur, categorie.titre, emprunt.date_emprunt, emprunt.date_retour 
        FROM abonne
        JOIN emprunt ON abonne.id = emprunt.abonne_id
        JOIN livre ON livre.id = emprunt.livre_id
        JOIN categorie ON categorie.id = livre.categorie_id
        WHERE abonne.id = app.user.id
         #}
        {% for emprunt in app.user.emprunts %}
            <tr>
            <td> {{emprunt.livre.titre}} {{emprunt.livre.auteur}}</td>
            <td> {{emprunt.livre.categorie.titre}}</td>
            <td> {{emprunt.dateEmprunt|date("d/m/Y")}} </td>
            <td>{{emprunt.dateRetour ? emprunt.dateRetour|date("d/m/Y") : "Emprunt en cours"}}</td>
            </tr>
        {% endfor %}
        </tbody>
	</table>

{% endblock %}